/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ConditionStatus = { 'New' : null } |
  { 'Fair' : null } |
  { 'Good' : null } |
  { 'Damaged' : null };
export interface Customer {
  'name' : string,
  'npwp' : string,
  'contactPerson' : string,
  'email' : string,
  'creditLimit' : bigint,
  'address' : string,
  'phone' : string,
}
export interface InventoryItem {
  'itemId' : string,
  'acquisitionCost' : bigint,
  'itemType' : ItemType,
  'quantity' : bigint,
  'location' : string,
  'condition' : ConditionStatus,
}
export type ItemType = { 'Pipe' : null } |
  { 'Board' : null } |
  { 'Frame' : null } |
  { 'Accessory' : null } |
  { 'Clamp' : null };
export interface RentalOrder {
  'status' : RentalOrderStatus,
  'endDate' : string,
  'orderId' : string,
  'customerId' : string,
  'itemIds' : Array<string>,
  'startDate' : string,
}
export type RentalOrderStatus = { 'Active' : null } |
  { 'Delivered' : null } |
  { 'Booked' : null } |
  { 'Returned' : null } |
  { 'QuotationApproved' : null };
export interface UserProfile {
  'name' : string,
  'role' : UserRole,
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Vendor {
  'bankAccount' : string,
  'npwp' : string,
  'contactPerson' : string,
  'email' : string,
  'address' : string,
  'companyName' : string,
  'paymentTerms' : bigint,
  'phone' : string,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCustomer' : ActorMethod<[Customer], undefined>,
  'addInventoryItem' : ActorMethod<[InventoryItem], undefined>,
  'addVendor' : ActorMethod<[Vendor], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createOrder' : ActorMethod<[RentalOrder], undefined>,
  'deleteCustomer' : ActorMethod<[string], undefined>,
  'deleteInventoryItem' : ActorMethod<[string], undefined>,
  'deleteOrder' : ActorMethod<[string], undefined>,
  'deleteVendor' : ActorMethod<[string], undefined>,
  'getAllOrders' : ActorMethod<[], Array<RentalOrder>>,
  'getCallerUserProfile' : ActorMethod<[], UserProfile>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCustomer' : ActorMethod<[string], Customer>,
  'getCustomers' : ActorMethod<[], Array<Customer>>,
  'getInventoryItem' : ActorMethod<[string], InventoryItem>,
  'getInventoryItems' : ActorMethod<[], Array<InventoryItem>>,
  'getOrder' : ActorMethod<[string], RentalOrder>,
  'getUserProfile' : ActorMethod<[Principal], UserProfile>,
  'getVendor' : ActorMethod<[string], Vendor>,
  'getVendors' : ActorMethod<[], Array<Vendor>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateCustomer' : ActorMethod<[string, Customer], undefined>,
  'updateInventoryItem' : ActorMethod<[string, InventoryItem], undefined>,
  'updateOrder' : ActorMethod<[string, RentalOrder], undefined>,
  'updateVendor' : ActorMethod<[string, Vendor], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];