/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Customer = IDL.Record({
  'name' : IDL.Text,
  'npwp' : IDL.Text,
  'contactPerson' : IDL.Text,
  'email' : IDL.Text,
  'creditLimit' : IDL.Nat,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const ItemType = IDL.Variant({
  'Pipe' : IDL.Null,
  'Board' : IDL.Null,
  'Frame' : IDL.Null,
  'Accessory' : IDL.Null,
  'Clamp' : IDL.Null,
});
export const ConditionStatus = IDL.Variant({
  'New' : IDL.Null,
  'Fair' : IDL.Null,
  'Good' : IDL.Null,
  'Damaged' : IDL.Null,
});
export const InventoryItem = IDL.Record({
  'itemId' : IDL.Text,
  'acquisitionCost' : IDL.Nat,
  'itemType' : ItemType,
  'quantity' : IDL.Nat,
  'location' : IDL.Text,
  'condition' : ConditionStatus,
});
export const Vendor = IDL.Record({
  'bankAccount' : IDL.Text,
  'npwp' : IDL.Text,
  'contactPerson' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'companyName' : IDL.Text,
  'paymentTerms' : IDL.Nat,
  'phone' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const RentalOrderStatus = IDL.Variant({
  'Active' : IDL.Null,
  'Delivered' : IDL.Null,
  'Booked' : IDL.Null,
  'Returned' : IDL.Null,
  'QuotationApproved' : IDL.Null,
});
export const RentalOrder = IDL.Record({
  'status' : RentalOrderStatus,
  'endDate' : IDL.Text,
  'orderId' : IDL.Text,
  'customerId' : IDL.Text,
  'itemIds' : IDL.Vec(IDL.Text),
  'startDate' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'role' : UserRole,
  'email' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCustomer' : IDL.Func([Customer], [], []),
  'addInventoryItem' : IDL.Func([InventoryItem], [], []),
  'addVendor' : IDL.Func([Vendor], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createOrder' : IDL.Func([RentalOrder], [], []),
  'deleteCustomer' : IDL.Func([IDL.Text], [], []),
  'deleteInventoryItem' : IDL.Func([IDL.Text], [], []),
  'deleteOrder' : IDL.Func([IDL.Text], [], []),
  'deleteVendor' : IDL.Func([IDL.Text], [], []),
  'getAllOrders' : IDL.Func([], [IDL.Vec(RentalOrder)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [UserProfile], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCustomer' : IDL.Func([IDL.Text], [Customer], ['query']),
  'getCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
  'getInventoryItem' : IDL.Func([IDL.Text], [InventoryItem], ['query']),
  'getInventoryItems' : IDL.Func([], [IDL.Vec(InventoryItem)], ['query']),
  'getOrder' : IDL.Func([IDL.Text], [RentalOrder], ['query']),
  'getUserProfile' : IDL.Func([IDL.Principal], [UserProfile], ['query']),
  'getVendor' : IDL.Func([IDL.Text], [Vendor], ['query']),
  'getVendors' : IDL.Func([], [IDL.Vec(Vendor)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateCustomer' : IDL.Func([IDL.Text, Customer], [], []),
  'updateInventoryItem' : IDL.Func([IDL.Text, InventoryItem], [], []),
  'updateOrder' : IDL.Func([IDL.Text, RentalOrder], [], []),
  'updateVendor' : IDL.Func([IDL.Text, Vendor], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Customer = IDL.Record({
    'name' : IDL.Text,
    'npwp' : IDL.Text,
    'contactPerson' : IDL.Text,
    'email' : IDL.Text,
    'creditLimit' : IDL.Nat,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const ItemType = IDL.Variant({
    'Pipe' : IDL.Null,
    'Board' : IDL.Null,
    'Frame' : IDL.Null,
    'Accessory' : IDL.Null,
    'Clamp' : IDL.Null,
  });
  const ConditionStatus = IDL.Variant({
    'New' : IDL.Null,
    'Fair' : IDL.Null,
    'Good' : IDL.Null,
    'Damaged' : IDL.Null,
  });
  const InventoryItem = IDL.Record({
    'itemId' : IDL.Text,
    'acquisitionCost' : IDL.Nat,
    'itemType' : ItemType,
    'quantity' : IDL.Nat,
    'location' : IDL.Text,
    'condition' : ConditionStatus,
  });
  const Vendor = IDL.Record({
    'bankAccount' : IDL.Text,
    'npwp' : IDL.Text,
    'contactPerson' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'companyName' : IDL.Text,
    'paymentTerms' : IDL.Nat,
    'phone' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const RentalOrderStatus = IDL.Variant({
    'Active' : IDL.Null,
    'Delivered' : IDL.Null,
    'Booked' : IDL.Null,
    'Returned' : IDL.Null,
    'QuotationApproved' : IDL.Null,
  });
  const RentalOrder = IDL.Record({
    'status' : RentalOrderStatus,
    'endDate' : IDL.Text,
    'orderId' : IDL.Text,
    'customerId' : IDL.Text,
    'itemIds' : IDL.Vec(IDL.Text),
    'startDate' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'role' : UserRole,
    'email' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCustomer' : IDL.Func([Customer], [], []),
    'addInventoryItem' : IDL.Func([InventoryItem], [], []),
    'addVendor' : IDL.Func([Vendor], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createOrder' : IDL.Func([RentalOrder], [], []),
    'deleteCustomer' : IDL.Func([IDL.Text], [], []),
    'deleteInventoryItem' : IDL.Func([IDL.Text], [], []),
    'deleteOrder' : IDL.Func([IDL.Text], [], []),
    'deleteVendor' : IDL.Func([IDL.Text], [], []),
    'getAllOrders' : IDL.Func([], [IDL.Vec(RentalOrder)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [UserProfile], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCustomer' : IDL.Func([IDL.Text], [Customer], ['query']),
    'getCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
    'getInventoryItem' : IDL.Func([IDL.Text], [InventoryItem], ['query']),
    'getInventoryItems' : IDL.Func([], [IDL.Vec(InventoryItem)], ['query']),
    'getOrder' : IDL.Func([IDL.Text], [RentalOrder], ['query']),
    'getUserProfile' : IDL.Func([IDL.Principal], [UserProfile], ['query']),
    'getVendor' : IDL.Func([IDL.Text], [Vendor], ['query']),
    'getVendors' : IDL.Func([], [IDL.Vec(Vendor)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateCustomer' : IDL.Func([IDL.Text, Customer], [], []),
    'updateInventoryItem' : IDL.Func([IDL.Text, InventoryItem], [], []),
    'updateOrder' : IDL.Func([IDL.Text, RentalOrder], [], []),
    'updateVendor' : IDL.Func([IDL.Text, Vendor], [], []),
  });
};

export const init = ({ IDL }) => { return []; };