/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface InventoryItem {
    itemId: string;
    acquisitionCost: bigint;
    itemType: ItemType;
    quantity: bigint;
    location: string;
    condition: ConditionStatus;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface RentalOrder {
    status: RentalOrderStatus;
    endDate: string;
    orderId: string;
    customerId: string;
    itemIds: Array<string>;
    startDate: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Vendor {
    bankAccount: string;
    npwp: string;
    contactPerson: string;
    email: string;
    address: string;
    companyName: string;
    paymentTerms: bigint;
    phone: string;
}
export interface Customer {
    name: string;
    npwp: string;
    contactPerson: string;
    email: string;
    creditLimit: bigint;
    address: string;
    phone: string;
}
export interface UserProfile {
    name: string;
    role: UserRole;
    email: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum ConditionStatus {
    New = "New",
    Fair = "Fair",
    Good = "Good",
    Damaged = "Damaged"
}
export enum ItemType {
    Pipe = "Pipe",
    Board = "Board",
    Frame = "Frame",
    Accessory = "Accessory",
    Clamp = "Clamp"
}
export enum RentalOrderStatus {
    Active = "Active",
    Delivered = "Delivered",
    Booked = "Booked",
    Returned = "Returned",
    QuotationApproved = "QuotationApproved"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addCustomer(customer: Customer): Promise<void>;
    addInventoryItem(item: InventoryItem): Promise<void>;
    addVendor(vendor: Vendor): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createOrder(order: RentalOrder): Promise<void>;
    deleteCustomer(npwp: string): Promise<void>;
    deleteInventoryItem(itemId: string): Promise<void>;
    deleteOrder(orderId: string): Promise<void>;
    deleteVendor(npwp: string): Promise<void>;
    getAllOrders(): Promise<Array<RentalOrder>>;
    getCallerUserProfile(): Promise<UserProfile>;
    getCallerUserRole(): Promise<UserRole>;
    getCustomer(npwp: string): Promise<Customer>;
    getCustomers(): Promise<Array<Customer>>;
    getInventoryItem(itemId: string): Promise<InventoryItem>;
    getInventoryItems(): Promise<Array<InventoryItem>>;
    getOrder(orderId: string): Promise<RentalOrder>;
    getUserProfile(user: Principal): Promise<UserProfile>;
    getVendor(npwp: string): Promise<Vendor>;
    getVendors(): Promise<Array<Vendor>>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateCustomer(npwp: string, customer: Customer): Promise<void>;
    updateInventoryItem(itemId: string, item: InventoryItem): Promise<void>;
    updateOrder(orderId: string, order: RentalOrder): Promise<void>;
    updateVendor(npwp: string, vendor: Vendor): Promise<void>;
}
import type { ConditionStatus as _ConditionStatus, InventoryItem as _InventoryItem, ItemType as _ItemType, RentalOrder as _RentalOrder, RentalOrderStatus as _RentalOrderStatus, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addCustomer(arg0: Customer): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addCustomer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCustomer(arg0);
            return result;
        }
    }
    async addInventoryItem(arg0: InventoryItem): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addInventoryItem(to_candid_InventoryItem_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addInventoryItem(to_candid_InventoryItem_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addVendor(arg0: Vendor): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addVendor(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addVendor(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n14(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n14(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createOrder(arg0: RentalOrder): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrder(to_candid_RentalOrder_n16(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrder(to_candid_RentalOrder_n16(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deleteCustomer(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCustomer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCustomer(arg0);
            return result;
        }
    }
    async deleteInventoryItem(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteInventoryItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteInventoryItem(arg0);
            return result;
        }
    }
    async deleteOrder(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteOrder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteOrder(arg0);
            return result;
        }
    }
    async deleteVendor(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteVendor(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteVendor(arg0);
            return result;
        }
    }
    async getAllOrders(): Promise<Array<RentalOrder>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllOrders();
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllOrders();
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_UserProfile_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_UserProfile_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCustomer(arg0: string): Promise<Customer> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomer(arg0);
            return result;
        }
    }
    async getCustomers(): Promise<Array<Customer>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomers();
            return result;
        }
    }
    async getInventoryItem(arg0: string): Promise<InventoryItem> {
        if (this.processError) {
            try {
                const result = await this.actor.getInventoryItem(arg0);
                return from_candid_InventoryItem_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInventoryItem(arg0);
            return from_candid_InventoryItem_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInventoryItems(): Promise<Array<InventoryItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInventoryItems();
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInventoryItems();
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrder(arg0: string): Promise<RentalOrder> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrder(arg0);
                return from_candid_RentalOrder_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrder(arg0);
            return from_candid_RentalOrder_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_UserProfile_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_UserProfile_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVendor(arg0: string): Promise<Vendor> {
        if (this.processError) {
            try {
                const result = await this.actor.getVendor(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVendor(arg0);
            return result;
        }
    }
    async getVendors(): Promise<Array<Vendor>> {
        if (this.processError) {
            try {
                const result = await this.actor.getVendors();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVendors();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n36(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n36(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateCustomer(arg0: string, arg1: Customer): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCustomer(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCustomer(arg0, arg1);
            return result;
        }
    }
    async updateInventoryItem(arg0: string, arg1: InventoryItem): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateInventoryItem(arg0, to_candid_InventoryItem_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateInventoryItem(arg0, to_candid_InventoryItem_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateOrder(arg0: string, arg1: RentalOrder): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOrder(arg0, to_candid_RentalOrder_n16(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOrder(arg0, to_candid_RentalOrder_n16(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateVendor(arg0: string, arg1: Vendor): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateVendor(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateVendor(arg0, arg1);
            return result;
        }
    }
}
function from_candid_ConditionStatus_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ConditionStatus): ConditionStatus {
    return from_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function from_candid_InventoryItem_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InventoryItem): InventoryItem {
    return from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid_ItemType_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ItemType): ItemType {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function from_candid_RentalOrderStatus_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RentalOrderStatus): RentalOrderStatus {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_RentalOrder_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RentalOrder): RentalOrder {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _RentalOrderStatus;
    endDate: string;
    orderId: string;
    customerId: string;
    itemIds: Array<string>;
    startDate: string;
}): {
    status: RentalOrderStatus;
    endDate: string;
    orderId: string;
    customerId: string;
    itemIds: Array<string>;
    startDate: string;
} {
    return {
        status: from_candid_RentalOrderStatus_n23(_uploadFile, _downloadFile, value.status),
        endDate: value.endDate,
        orderId: value.orderId,
        customerId: value.customerId,
        itemIds: value.itemIds,
        startDate: value.startDate
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    role: _UserRole;
    email: string;
}): {
    name: string;
    role: UserRole;
    email: string;
} {
    return {
        name: value.name,
        role: from_candid_UserRole_n27(_uploadFile, _downloadFile, value.role),
        email: value.email
    };
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    itemId: string;
    acquisitionCost: bigint;
    itemType: _ItemType;
    quantity: bigint;
    location: string;
    condition: _ConditionStatus;
}): {
    itemId: string;
    acquisitionCost: bigint;
    itemType: ItemType;
    quantity: bigint;
    location: string;
    condition: ConditionStatus;
} {
    return {
        itemId: value.itemId,
        acquisitionCost: value.acquisitionCost,
        itemType: from_candid_ItemType_n31(_uploadFile, _downloadFile, value.itemType),
        quantity: value.quantity,
        location: value.location,
        condition: from_candid_ConditionStatus_n33(_uploadFile, _downloadFile, value.condition)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Active: null;
} | {
    Delivered: null;
} | {
    Booked: null;
} | {
    Returned: null;
} | {
    QuotationApproved: null;
}): RentalOrderStatus {
    return "Active" in value ? RentalOrderStatus.Active : "Delivered" in value ? RentalOrderStatus.Delivered : "Booked" in value ? RentalOrderStatus.Booked : "Returned" in value ? RentalOrderStatus.Returned : "QuotationApproved" in value ? RentalOrderStatus.QuotationApproved : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Pipe: null;
} | {
    Board: null;
} | {
    Frame: null;
} | {
    Accessory: null;
} | {
    Clamp: null;
}): ItemType {
    return "Pipe" in value ? ItemType.Pipe : "Board" in value ? ItemType.Board : "Frame" in value ? ItemType.Frame : "Accessory" in value ? ItemType.Accessory : "Clamp" in value ? ItemType.Clamp : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    New: null;
} | {
    Fair: null;
} | {
    Good: null;
} | {
    Damaged: null;
}): ConditionStatus {
    return "New" in value ? ConditionStatus.New : "Fair" in value ? ConditionStatus.Fair : "Good" in value ? ConditionStatus.Good : "Damaged" in value ? ConditionStatus.Damaged : value;
}
function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_RentalOrder>): Array<RentalOrder> {
    return value.map((x)=>from_candid_RentalOrder_n21(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_InventoryItem>): Array<InventoryItem> {
    return value.map((x)=>from_candid_InventoryItem_n29(_uploadFile, _downloadFile, x));
}
function to_candid_ConditionStatus_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ConditionStatus): _ConditionStatus {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_InventoryItem_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InventoryItem): _InventoryItem {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_ItemType_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ItemType): _ItemType {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_RentalOrderStatus_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RentalOrderStatus): _RentalOrderStatus {
    return to_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function to_candid_RentalOrder_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RentalOrder): _RentalOrder {
    return to_candid_record_n17(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n37(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: RentalOrderStatus;
    endDate: string;
    orderId: string;
    customerId: string;
    itemIds: Array<string>;
    startDate: string;
}): {
    status: _RentalOrderStatus;
    endDate: string;
    orderId: string;
    customerId: string;
    itemIds: Array<string>;
    startDate: string;
} {
    return {
        status: to_candid_RentalOrderStatus_n18(_uploadFile, _downloadFile, value.status),
        endDate: value.endDate,
        orderId: value.orderId,
        customerId: value.customerId,
        itemIds: value.itemIds,
        startDate: value.startDate
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    role: UserRole;
    email: string;
}): {
    name: string;
    role: _UserRole;
    email: string;
} {
    return {
        name: value.name,
        role: to_candid_UserRole_n14(_uploadFile, _downloadFile, value.role),
        email: value.email
    };
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    itemId: string;
    acquisitionCost: bigint;
    itemType: ItemType;
    quantity: bigint;
    location: string;
    condition: ConditionStatus;
}): {
    itemId: string;
    acquisitionCost: bigint;
    itemType: _ItemType;
    quantity: bigint;
    location: string;
    condition: _ConditionStatus;
} {
    return {
        itemId: value.itemId,
        acquisitionCost: value.acquisitionCost,
        itemType: to_candid_ItemType_n10(_uploadFile, _downloadFile, value.itemType),
        quantity: value.quantity,
        location: value.location,
        condition: to_candid_ConditionStatus_n12(_uploadFile, _downloadFile, value.condition)
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ItemType): {
    Pipe: null;
} | {
    Board: null;
} | {
    Frame: null;
} | {
    Accessory: null;
} | {
    Clamp: null;
} {
    return value == ItemType.Pipe ? {
        Pipe: null
    } : value == ItemType.Board ? {
        Board: null
    } : value == ItemType.Frame ? {
        Frame: null
    } : value == ItemType.Accessory ? {
        Accessory: null
    } : value == ItemType.Clamp ? {
        Clamp: null
    } : value;
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ConditionStatus): {
    New: null;
} | {
    Fair: null;
} | {
    Good: null;
} | {
    Damaged: null;
} {
    return value == ConditionStatus.New ? {
        New: null
    } : value == ConditionStatus.Fair ? {
        Fair: null
    } : value == ConditionStatus.Good ? {
        Good: null
    } : value == ConditionStatus.Damaged ? {
        Damaged: null
    } : value;
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RentalOrderStatus): {
    Active: null;
} | {
    Delivered: null;
} | {
    Booked: null;
} | {
    Returned: null;
} | {
    QuotationApproved: null;
} {
    return value == RentalOrderStatus.Active ? {
        Active: null
    } : value == RentalOrderStatus.Delivered ? {
        Delivered: null
    } : value == RentalOrderStatus.Booked ? {
        Booked: null
    } : value == RentalOrderStatus.Returned ? {
        Returned: null
    } : value == RentalOrderStatus.QuotationApproved ? {
        QuotationApproved: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
